export const products = [
  {
    id: 1,
    src: "./bike1.jpg",
    title: "Rodado 20",
    price: "20,000",
    description: "Bicicleta rodado 26 doble suspension",
    category: { bicicletas: { rodado: 26 } },
  },
  {
    id: 2,
    src: "./bike2.jpg",
    title: "Rodado 26",
    price: "25,000",
    description: "Bicicleta marca Jordan rodado 29 aluminio",
    category: { bicicletas: { rodado: 29 } },
  },
  {
    id: 3,
    src: "./bike3.jpg",
    title: "Rodado 16",
    price: "15,000",
    description: "Bicicleta rodado 20 doble suspension",
    category: { bicicletas: { rodado: 20 } },
  },
  {
    id: 4,
    src: "./bike4.jpg",
    title: "Rodado 12",
    price: "10,000",
    description: "Bicicleta tipo moto rodado 16",
    category: { bicicletas: { rodado: 16 } },
  },
  {
    id: 5,
    src: "./roller1.jpg",
    title: "Rollers SBK",
    price: "7,000",
    description: "Rollers SBK",
    category: { rollers: true },
  },
  {
    id: 6,
    src: "./roller2.jpg",
    title: "Rollers Shine",
    price: "5,000",
    description: "Rollers Shine",
    category: { rollers: true },
  },
];
